[features]
seeds = false
skip-lint = false
[programs.localnet]
tweet_sol = "7AUJ9r93pB1mAXDvWDZ5YmgJqJW9aoCrjUXsne6KuvTP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/lol/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
